# Each letter represents a colour marker:
#   k, r, g, y, b, m, c, w, d
# which stands for:
#   blacK, Red, Green, Yellow, Blue, Magenta, Cyan, White, Default
# Capital letters represent bold
# Copy to ~/.bpython/foo.theme and set "color_scheme = foo" in
# ~/.bpython/config

[syntax]
keyword = B
name = m
comment = w
string = g
error = r
number = G
operator = w
paren = w
punctuation = w
token = d

[interface]
background = d
output = w
main = w
prompt = w
prompt_more = g
