#!/usr/bin/env bash

script=$(dirname $0)/status.py
# Placeholder summary, which is ignored by `dunstrc`. This is due to
# the behavior in dunst 1.4.1 in which markup in the summary is
# not supported: https://github.com/dunst-project/dunst/issues/616
notify-send "PLACEHOLDER" "$(${script})"
